server:
  port: 80
logging:
  level:
    com: debug

spring:
  config:
    import:
      - dbconfig.yml
      - jwt.yml
      - security.yml

  messages:
    basename: messages
  devtools:
    livereload:
      enabled: true