server:
  port: 80
logging:
  level:
    com: debug
jwt:
  header: Authorization
  refreshtoken-validity-in-seconds: 2419200000
  accesstoken-validity-in-seconds: 1800000
  secret:

spring:
  config:
    import: dbconfig.yml
  messages:
    basename: messages
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 300
  devtools:
    livereload:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret:
            scope:
              - email
              - profile
          kakao:
            client-id:
            client-secret:
            redirect-uri: http://localhost:80/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          naver:
            client-id:
            client-secret:
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:80/login/oauth2/code/naver # redirect 할 URI

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원 정보를 json으로 받는데 response라는 키 값으로 네이버가 리턴해줌.

app:
  oauth2:
    authorizedRedirectUri: http://localhost:3000/oauth2/redirect