server:
  port: 8085
logging:
  level:
    com: info
app:
  image-size: 8
  video-size: 4
  style-tag-size: 5

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none